Use master
go
create database Dental_Clinic
go

use Dental_Clinic
go

CREATE TABLE PATIENT (
	PATIENT_ID CHAR(10),
	FULL_NAME VARCHAR(30),
	DOB DATE,
	GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
	ALLERGIES VARCHAR(30),
	CONTRAINDICATION VARCHAR(30),
	CONSTRAINT PK_PATIENT PRIMARY KEY(PATIENT_ID),
	)

CREATE TABLE TREATMENT (
	TREATMENT_ID CHAR(9),
	DENTIST_ID CHAR(10),
	ASSISTANT_ID CHAR(10),
	PATIENT_ID CHAR(10),
	TREATMENT_STATUS VARCHAR(10),
	CONSTRAINT PK_TREATMENT PRIMARY KEY(TREATMENT_ID),
	)

CREATE TABLE APPOINTMENT (
	APPOINTMENT_ID CHAR(9),
	TREATMENT_ID CHAR(9),
	ROOM VARCHAR(4),
	APPOINTMENT_STATUS VARCHAR(10),
	APPOINTMENT_SCHEDULE DATETIME,
	CONSTRAINT PK_APPOINTMENT PRIMARY KEY(APPOINTMENT_ID, TREATMENT_ID),
	)

CREATE TABLE DENTIST (
	DENTIST_ID CHAR(10),
	FULL_NAME VARCHAR(30),
	DOB DATE,
	GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
	EMAIL_ADDRESS VARCHAR(30),
	NOTES VARCHAR(30),
	CONSTRAINT PK_DENTIST PRIMARY KEY(DENTIST_ID),
	)

CREATE TABLE PRESCRIPTION (
	PRESCRIPTION_ID CHAR(9), 
	NOTES VARCHAR(30),
	APPOINTMENT_ID CHAR(9),
	TREATMENT_ID CHAR(9),
	CONSTRAINT PK_PRESCRIPTION PRIMARY KEY(PRESCRIPTION_ID),
	)

CREATE TABLE MEDICINE_IN_PRESCRIPTION (
	PRESCRIPTION_ID CHAR(9),
	MEDICINE_ID CHAR(9),
	QUANTIY INT,
	CONSTRAINT PK_MED_IN_PRES PRIMARY KEY(PRESCRIPTION_ID, MEDICINE_ID),
	)

CREATE TABLE MEDICINE (
	MEDICINE_ID CHAR(9),
	NAME VARCHAR(30),
	MEDICINE_DESCRIPTION VARCHAR(30),
	CONSTRAINT PK_MEDICINE PRIMARY KEY(MEDICINE_ID),
	)

CREATE TABLE INVOICE (
	INVOICE_ID CHAR(9),
	PAYER_NAME VARCHAR(30),
	PAID_FEE MONEY,
	FEE MONEY,
	FEE_CHANGE MONEY,
	PAYMENT_METHOD VARCHAR(12),
	APPOINTMENT_ID CHAR(9),
	TREATMENT_ID CHAR(9),
	CONSTRAINT PK_INVOICE PRIMARY KEY(INVOICE_ID),
	)

CREATE TABLE REQUEST (
	REQUEST_ID CHAR(9),
	PATIENT_ID CHAR(10),
	NOTES VARCHAR(30),
	SEND_DATE DATETIME,
	REQUEST_STATUS VARCHAR(10),
	CONSTRAINT PK_REQUEST PRIMARY KEY(REQUEST_ID),
	)

CREATE TABLE APPROVED_REQUEST (
	REQUEST_ID CHAR(9),
	STAFF_ID CHAR(10),
	CONSTRAINT PK_APPROVE_REQUEST PRIMARY KEY(REQUEST_ID, STAFF_ID),
	)

CREATE TABLE STAFF (
	STAFF_ID CHAR(10),
	FULL_NAME VARCHAR(30),
	GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
	EMAIL_ADDRESS VARCHAR(30),
	NOTES VARCHAR(30),
	CONSTRAINT PK_STAFF PRIMARY KEY(STAFF_ID),
	)

CREATE TABLE SCHEDULE_FOR_EMPLOYEE (
	EMPLOYEE_ID CHAR(10),
	SCHEDULE DATETIME,
	CONSTRAINT PK_SCHEDULE PRIMARY KEY(EMPLOYEE_ID, SCHEDULE),
	)

ALTER TABLE MEDICINE_IN_PRESCRIPTION
ADD CONSTRAINT FK_MEDINPRES_PRESCRIPTION
FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID);

ALTER TABLE MEDICINE_IN_PRESCRIPTION
ADD CONSTRAINT FK_MEDINPRES_MEDICINE
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID);

ALTER TABLE PRESCRIPTION
ADD CONSTRAINT FK_PRESCRIPTION_APPOINTMENT
FOREIGN KEY (APPOINTMENT_ID, TREATMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID, TREATMENT_ID);

ALTER TABLE INVOICE
ADD CONSTRAINT FK_INVOICE_APPOINTMENT
FOREIGN KEY (APPOINTMENT_ID, TREATMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID, TREATMENT_ID);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_TREATMENT
FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_PATIENT
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_DENTIST
FOREIGN KEY (DENTIST_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE TREATMENT
ADD CONSTRAINT FK_TREATMENT_ASSISTANT
FOREIGN KEY (ASSISTANT_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE REQUEST
ADD CONSTRAINT FK_REQUEST_PATIENT
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID);

ALTER TABLE APPROVED_REQUEST
ADD CONSTRAINT FK_APPREQ_REQUEST
FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST(REQUEST_ID);

ALTER TABLE APPROVED_REQUEST
ADD CONSTRAINT FK_APPREQ_STAFF
FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE SCHEDULE_FOR_EMPLOYEE
ADD CONSTRAINT FK_SCHEDULE_DENTIST
FOREIGN KEY (EMPLOYEE_ID) REFERENCES DENTIST(DENTIST_ID);

ALTER TABLE SCHEDULE_FOR_EMPLOYEE
ADD CONSTRAINT FK_SCHEDULE_STAFF
FOREIGN KEY (EMPLOYEE_ID) REFERENCES STAFF(STAFF_ID);

